name: Android Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk

      - name: Save APK
        run: mkdir -p apk && cp build/app/outputs/flutter-apk/app-release.apk apk/
      # This command creates a directory named "apk" and copies the generated APK to that directory.

      - name: Commit APK
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add apk/
          git commit -m "Add APK"